// Annual SG&A breakdown from notes in 사업보고서
// Unit: 백만원
// Source: DART annual reports, SGA expense notes (section 24.1 or 25.1)
// Item identification based on magnitude and K-IFRS standard ordering
// Generated by extract_financials.py

export interface FaduSgaBreakdown {
  year: number;            // 2023, 2024, 2025
  total: number;          // matches income-statement SGA sum

  salary: number | null;           // 급여
  pension: number | null;          // 퇴직급여
  welfare: number | null;          // 복리후생비
  stockComp: number | null;        // 주식보상비용
  depreciation: number | null;     // 감가상각비
  rouDepreciation: number | null;  // 사용권자산감가상각비
  amortization: number | null;     // 무형자산상각비
  rnd: number | null;              // 연구개발비
  serviceFees: number | null;      // 지급수수료
  other: number | null;            // 기타
}

export const faduSgaBreakdown: FaduSgaBreakdown[] = [
  // 2023FY SGA breakdown from annual report notes
  {
    year: 2023,
    total: 69665,
    salary: 7280,
    pension: 441,
    welfare: 2075,
    stockComp: 5130,
    depreciation: 626,
    rouDepreciation: 117,
    amortization: 21,
    rnd: 51742,
    serviceFees: 214,
    other: 2022,
  },
  // 2024FY SGA breakdown from annual report notes
  {
    year: 2024,
    total: 100817,
    salary: 11768,
    pension: 511,
    welfare: 2914,
    stockComp: 13225,
    depreciation: 915,
    rouDepreciation: 241,
    amortization: 39,
    rnd: 66093,
    serviceFees: 526,
    other: 4585,
  },
  // 2025FY SGA breakdown from annual report notes
  {
    year: 2025,
    total: 109128,
    salary: 17120,
    pension: 961,
    welfare: 3966,
    stockComp: 12170,
    depreciation: 1012,
    rouDepreciation: 228,
    amortization: 52,
    rnd: 68716,
    serviceFees: 664,
    other: 4241,
  }
];
